// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: wf_spec.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

@com.google.protobuf.Generated
public interface InlineWfSpecDefinitionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.InlineWfSpecDefinition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  int getThreadSpecsCount();
  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  boolean containsThreadSpecs(
      java.lang.String key);
  /**
   * Use {@link #getThreadSpecsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec>
  getThreadSpecs();
  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec>
  getThreadSpecsMap();
  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  /* nullable */
io.littlehorse.sdk.common.proto.ThreadSpec getThreadSpecsOrDefault(
      java.lang.String key,
      /* nullable */
io.littlehorse.sdk.common.proto.ThreadSpec defaultValue);
  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  io.littlehorse.sdk.common.proto.ThreadSpec getThreadSpecsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * ThreadSpec used as the workflow entrypoint.
   * </pre>
   *
   * <code>string entrypoint_thread_name = 2;</code>
   * @return The entrypointThreadName.
   */
  java.lang.String getEntrypointThreadName();
  /**
   * <pre>
   * ThreadSpec used as the workflow entrypoint.
   * </pre>
   *
   * <code>string entrypoint_thread_name = 2;</code>
   * @return The bytes for entrypointThreadName.
   */
  com.google.protobuf.ByteString
      getEntrypointThreadNameBytes();

  /**
   * <pre>
   * Controls cleanup of the owning WfRun after it terminates.
   * </pre>
   *
   * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
   * @return Whether the retentionPolicy field is set.
   */
  boolean hasRetentionPolicy();
  /**
   * <pre>
   * Controls cleanup of the owning WfRun after it terminates.
   * </pre>
   *
   * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
   * @return The retentionPolicy.
   */
  io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy getRetentionPolicy();
  /**
   * <pre>
   * Controls cleanup of the owning WfRun after it terminates.
   * </pre>
   *
   * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
   */
  io.littlehorse.sdk.common.proto.WorkflowRetentionPolicyOrBuilder getRetentionPolicyOrBuilder();
}
