// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: wf_spec.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

/**
 * <pre>
 * A caller-provided workflow definition that is executed by exactly one WfRun.
 *
 * Unlike a WfSpec, this definition is not registered, named, versioned,
 * searchable, updated, or independently addressable.
 * </pre>
 *
 * Protobuf type {@code littlehorse.InlineWfSpecDefinition}
 */
@com.google.protobuf.Generated
public final class InlineWfSpecDefinition extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:littlehorse.InlineWfSpecDefinition)
    InlineWfSpecDefinitionOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      InlineWfSpecDefinition.class.getName());
  }
  // Use InlineWfSpecDefinition.newBuilder() to construct.
  private InlineWfSpecDefinition(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InlineWfSpecDefinition() {
    entrypointThreadName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpecDefinition_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetThreadSpecs();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpecDefinition_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.class, io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.Builder.class);
  }

  private int bitField0_;
  public static final int THREAD_SPECS_FIELD_NUMBER = 1;
  private static final class ThreadSpecsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec>newDefaultInstance(
                io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpecDefinition_ThreadSpecsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.littlehorse.sdk.common.proto.ThreadSpec.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> threadSpecs_;
  private com.google.protobuf.MapField<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec>
  internalGetThreadSpecs() {
    if (threadSpecs_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ThreadSpecsDefaultEntryHolder.defaultEntry);
    }
    return threadSpecs_;
  }
  public int getThreadSpecsCount() {
    return internalGetThreadSpecs().getMap().size();
  }
  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  @java.lang.Override
  public boolean containsThreadSpecs(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetThreadSpecs().getMap().containsKey(key);
  }
  /**
   * Use {@link #getThreadSpecsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> getThreadSpecs() {
    return getThreadSpecsMap();
  }
  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> getThreadSpecsMap() {
    return internalGetThreadSpecs().getMap();
  }
  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
io.littlehorse.sdk.common.proto.ThreadSpec getThreadSpecsOrDefault(
      java.lang.String key,
      /* nullable */
io.littlehorse.sdk.common.proto.ThreadSpec defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> map =
        internalGetThreadSpecs().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * ThreadSpecs that comprise the workflow.
   * </pre>
   *
   * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.ThreadSpec getThreadSpecsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> map =
        internalGetThreadSpecs().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int ENTRYPOINT_THREAD_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object entrypointThreadName_ = "";
  /**
   * <pre>
   * ThreadSpec used as the workflow entrypoint.
   * </pre>
   *
   * <code>string entrypoint_thread_name = 2;</code>
   * @return The entrypointThreadName.
   */
  @java.lang.Override
  public java.lang.String getEntrypointThreadName() {
    java.lang.Object ref = entrypointThreadName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      entrypointThreadName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ThreadSpec used as the workflow entrypoint.
   * </pre>
   *
   * <code>string entrypoint_thread_name = 2;</code>
   * @return The bytes for entrypointThreadName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntrypointThreadNameBytes() {
    java.lang.Object ref = entrypointThreadName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entrypointThreadName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETENTION_POLICY_FIELD_NUMBER = 3;
  private io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy retentionPolicy_;
  /**
   * <pre>
   * Controls cleanup of the owning WfRun after it terminates.
   * </pre>
   *
   * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
   * @return Whether the retentionPolicy field is set.
   */
  @java.lang.Override
  public boolean hasRetentionPolicy() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Controls cleanup of the owning WfRun after it terminates.
   * </pre>
   *
   * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
   * @return The retentionPolicy.
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy getRetentionPolicy() {
    return retentionPolicy_ == null ? io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.getDefaultInstance() : retentionPolicy_;
  }
  /**
   * <pre>
   * Controls cleanup of the owning WfRun after it terminates.
   * </pre>
   *
   * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.WorkflowRetentionPolicyOrBuilder getRetentionPolicyOrBuilder() {
    return retentionPolicy_ == null ? io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.getDefaultInstance() : retentionPolicy_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetThreadSpecs(),
        ThreadSpecsDefaultEntryHolder.defaultEntry,
        1);
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(entrypointThreadName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, entrypointThreadName_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getRetentionPolicy());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> entry
         : internalGetThreadSpecs().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec>
      threadSpecs__ = ThreadSpecsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, threadSpecs__);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(entrypointThreadName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, entrypointThreadName_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRetentionPolicy());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.sdk.common.proto.InlineWfSpecDefinition)) {
      return super.equals(obj);
    }
    io.littlehorse.sdk.common.proto.InlineWfSpecDefinition other = (io.littlehorse.sdk.common.proto.InlineWfSpecDefinition) obj;

    if (!internalGetThreadSpecs().equals(
        other.internalGetThreadSpecs())) return false;
    if (!getEntrypointThreadName()
        .equals(other.getEntrypointThreadName())) return false;
    if (hasRetentionPolicy() != other.hasRetentionPolicy()) return false;
    if (hasRetentionPolicy()) {
      if (!getRetentionPolicy()
          .equals(other.getRetentionPolicy())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetThreadSpecs().getMap().isEmpty()) {
      hash = (37 * hash) + THREAD_SPECS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetThreadSpecs().hashCode();
    }
    hash = (37 * hash) + ENTRYPOINT_THREAD_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEntrypointThreadName().hashCode();
    if (hasRetentionPolicy()) {
      hash = (37 * hash) + RETENTION_POLICY_FIELD_NUMBER;
      hash = (53 * hash) + getRetentionPolicy().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.sdk.common.proto.InlineWfSpecDefinition prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A caller-provided workflow definition that is executed by exactly one WfRun.
   *
   * Unlike a WfSpec, this definition is not registered, named, versioned,
   * searchable, updated, or independently addressable.
   * </pre>
   *
   * Protobuf type {@code littlehorse.InlineWfSpecDefinition}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:littlehorse.InlineWfSpecDefinition)
      io.littlehorse.sdk.common.proto.InlineWfSpecDefinitionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpecDefinition_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetThreadSpecs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableThreadSpecs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpecDefinition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.class, io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.Builder.class);
    }

    // Construct using io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRetentionPolicyFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableThreadSpecs().clear();
      entrypointThreadName_ = "";
      retentionPolicy_ = null;
      if (retentionPolicyBuilder_ != null) {
        retentionPolicyBuilder_.dispose();
        retentionPolicyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpecDefinition_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.InlineWfSpecDefinition getDefaultInstanceForType() {
      return io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.InlineWfSpecDefinition build() {
      io.littlehorse.sdk.common.proto.InlineWfSpecDefinition result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.InlineWfSpecDefinition buildPartial() {
      io.littlehorse.sdk.common.proto.InlineWfSpecDefinition result = new io.littlehorse.sdk.common.proto.InlineWfSpecDefinition(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.littlehorse.sdk.common.proto.InlineWfSpecDefinition result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.threadSpecs_ = internalGetThreadSpecs().build(ThreadSpecsDefaultEntryHolder.defaultEntry);
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.entrypointThreadName_ = entrypointThreadName_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.retentionPolicy_ = retentionPolicyBuilder_ == null
            ? retentionPolicy_
            : retentionPolicyBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.sdk.common.proto.InlineWfSpecDefinition) {
        return mergeFrom((io.littlehorse.sdk.common.proto.InlineWfSpecDefinition)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.sdk.common.proto.InlineWfSpecDefinition other) {
      if (other == io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.getDefaultInstance()) return this;
      internalGetMutableThreadSpecs().mergeFrom(
          other.internalGetThreadSpecs());
      bitField0_ |= 0x00000001;
      if (!other.getEntrypointThreadName().isEmpty()) {
        entrypointThreadName_ = other.entrypointThreadName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasRetentionPolicy()) {
        mergeRetentionPolicy(other.getRetentionPolicy());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec>
              threadSpecs__ = input.readMessage(
                  ThreadSpecsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableThreadSpecs().ensureBuilderMap().put(
                  threadSpecs__.getKey(), threadSpecs__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              entrypointThreadName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetRetentionPolicyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class ThreadSpecsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder, io.littlehorse.sdk.common.proto.ThreadSpec> {
      @java.lang.Override
      public io.littlehorse.sdk.common.proto.ThreadSpec build(io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder val) {
        if (val instanceof io.littlehorse.sdk.common.proto.ThreadSpec) { return (io.littlehorse.sdk.common.proto.ThreadSpec) val; }
        return ((io.littlehorse.sdk.common.proto.ThreadSpec.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> defaultEntry() {
        return ThreadSpecsDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ThreadSpecsConverter threadSpecsConverter = new ThreadSpecsConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder, io.littlehorse.sdk.common.proto.ThreadSpec, io.littlehorse.sdk.common.proto.ThreadSpec.Builder> threadSpecs_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder, io.littlehorse.sdk.common.proto.ThreadSpec, io.littlehorse.sdk.common.proto.ThreadSpec.Builder>
        internalGetThreadSpecs() {
      if (threadSpecs_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(threadSpecsConverter);
      }
      return threadSpecs_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder, io.littlehorse.sdk.common.proto.ThreadSpec, io.littlehorse.sdk.common.proto.ThreadSpec.Builder>
        internalGetMutableThreadSpecs() {
      if (threadSpecs_ == null) {
        threadSpecs_ = new com.google.protobuf.MapFieldBuilder<>(threadSpecsConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return threadSpecs_;
    }
    public int getThreadSpecsCount() {
      return internalGetThreadSpecs().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * ThreadSpecs that comprise the workflow.
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
     */
    @java.lang.Override
    public boolean containsThreadSpecs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetThreadSpecs().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getThreadSpecsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> getThreadSpecs() {
      return getThreadSpecsMap();
    }
    /**
     * <pre>
     * ThreadSpecs that comprise the workflow.
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> getThreadSpecsMap() {
      return internalGetThreadSpecs().getImmutableMap();
    }
    /**
     * <pre>
     * ThreadSpecs that comprise the workflow.
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
io.littlehorse.sdk.common.proto.ThreadSpec getThreadSpecsOrDefault(
        java.lang.String key,
        /* nullable */
io.littlehorse.sdk.common.proto.ThreadSpec defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder> map = internalGetMutableThreadSpecs().ensureBuilderMap();
      return map.containsKey(key) ? threadSpecsConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * ThreadSpecs that comprise the workflow.
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
     */
    @java.lang.Override
    public io.littlehorse.sdk.common.proto.ThreadSpec getThreadSpecsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder> map = internalGetMutableThreadSpecs().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return threadSpecsConverter.build(map.get(key));
    }
    public Builder clearThreadSpecs() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableThreadSpecs().clear();
      return this;
    }
    /**
     * <pre>
     * ThreadSpecs that comprise the workflow.
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
     */
    public Builder removeThreadSpecs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableThreadSpecs().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec>
        getMutableThreadSpecs() {
      bitField0_ |= 0x00000001;
      return internalGetMutableThreadSpecs().ensureMessageMap();
    }
    /**
     * <pre>
     * ThreadSpecs that comprise the workflow.
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
     */
    public Builder putThreadSpecs(
        java.lang.String key,
        io.littlehorse.sdk.common.proto.ThreadSpec value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableThreadSpecs().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * ThreadSpecs that comprise the workflow.
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
     */
    public Builder putAllThreadSpecs(
        java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> values) {
      for (java.util.Map.Entry<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpec> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableThreadSpecs().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * ThreadSpecs that comprise the workflow.
     * </pre>
     *
     * <code>map&lt;string, .littlehorse.ThreadSpec&gt; thread_specs = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.ThreadSpec.Builder putThreadSpecsBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder> builderMap = internalGetMutableThreadSpecs().ensureBuilderMap();
      io.littlehorse.sdk.common.proto.ThreadSpecOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = io.littlehorse.sdk.common.proto.ThreadSpec.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof io.littlehorse.sdk.common.proto.ThreadSpec) {
        entry = ((io.littlehorse.sdk.common.proto.ThreadSpec) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (io.littlehorse.sdk.common.proto.ThreadSpec.Builder) entry;
    }

    private java.lang.Object entrypointThreadName_ = "";
    /**
     * <pre>
     * ThreadSpec used as the workflow entrypoint.
     * </pre>
     *
     * <code>string entrypoint_thread_name = 2;</code>
     * @return The entrypointThreadName.
     */
    public java.lang.String getEntrypointThreadName() {
      java.lang.Object ref = entrypointThreadName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        entrypointThreadName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ThreadSpec used as the workflow entrypoint.
     * </pre>
     *
     * <code>string entrypoint_thread_name = 2;</code>
     * @return The bytes for entrypointThreadName.
     */
    public com.google.protobuf.ByteString
        getEntrypointThreadNameBytes() {
      java.lang.Object ref = entrypointThreadName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entrypointThreadName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ThreadSpec used as the workflow entrypoint.
     * </pre>
     *
     * <code>string entrypoint_thread_name = 2;</code>
     * @param value The entrypointThreadName to set.
     * @return This builder for chaining.
     */
    public Builder setEntrypointThreadName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      entrypointThreadName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ThreadSpec used as the workflow entrypoint.
     * </pre>
     *
     * <code>string entrypoint_thread_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntrypointThreadName() {
      entrypointThreadName_ = getDefaultInstance().getEntrypointThreadName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ThreadSpec used as the workflow entrypoint.
     * </pre>
     *
     * <code>string entrypoint_thread_name = 2;</code>
     * @param value The bytes for entrypointThreadName to set.
     * @return This builder for chaining.
     */
    public Builder setEntrypointThreadNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      entrypointThreadName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy retentionPolicy_;
    private com.google.protobuf.SingleFieldBuilder<
        io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy, io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.Builder, io.littlehorse.sdk.common.proto.WorkflowRetentionPolicyOrBuilder> retentionPolicyBuilder_;
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     * @return Whether the retentionPolicy field is set.
     */
    public boolean hasRetentionPolicy() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     * @return The retentionPolicy.
     */
    public io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy getRetentionPolicy() {
      if (retentionPolicyBuilder_ == null) {
        return retentionPolicy_ == null ? io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.getDefaultInstance() : retentionPolicy_;
      } else {
        return retentionPolicyBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     */
    public Builder setRetentionPolicy(io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy value) {
      if (retentionPolicyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        retentionPolicy_ = value;
      } else {
        retentionPolicyBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     */
    public Builder setRetentionPolicy(
        io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.Builder builderForValue) {
      if (retentionPolicyBuilder_ == null) {
        retentionPolicy_ = builderForValue.build();
      } else {
        retentionPolicyBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     */
    public Builder mergeRetentionPolicy(io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy value) {
      if (retentionPolicyBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          retentionPolicy_ != null &&
          retentionPolicy_ != io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.getDefaultInstance()) {
          getRetentionPolicyBuilder().mergeFrom(value);
        } else {
          retentionPolicy_ = value;
        }
      } else {
        retentionPolicyBuilder_.mergeFrom(value);
      }
      if (retentionPolicy_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     */
    public Builder clearRetentionPolicy() {
      bitField0_ = (bitField0_ & ~0x00000004);
      retentionPolicy_ = null;
      if (retentionPolicyBuilder_ != null) {
        retentionPolicyBuilder_.dispose();
        retentionPolicyBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     */
    public io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.Builder getRetentionPolicyBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetRetentionPolicyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     */
    public io.littlehorse.sdk.common.proto.WorkflowRetentionPolicyOrBuilder getRetentionPolicyOrBuilder() {
      if (retentionPolicyBuilder_ != null) {
        return retentionPolicyBuilder_.getMessageOrBuilder();
      } else {
        return retentionPolicy_ == null ?
            io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.getDefaultInstance() : retentionPolicy_;
      }
    }
    /**
     * <pre>
     * Controls cleanup of the owning WfRun after it terminates.
     * </pre>
     *
     * <code>optional .littlehorse.WorkflowRetentionPolicy retention_policy = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy, io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.Builder, io.littlehorse.sdk.common.proto.WorkflowRetentionPolicyOrBuilder> 
        internalGetRetentionPolicyFieldBuilder() {
      if (retentionPolicyBuilder_ == null) {
        retentionPolicyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy, io.littlehorse.sdk.common.proto.WorkflowRetentionPolicy.Builder, io.littlehorse.sdk.common.proto.WorkflowRetentionPolicyOrBuilder>(
                getRetentionPolicy(),
                getParentForChildren(),
                isClean());
        retentionPolicy_ = null;
      }
      return retentionPolicyBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:littlehorse.InlineWfSpecDefinition)
  }

  // @@protoc_insertion_point(class_scope:littlehorse.InlineWfSpecDefinition)
  private static final io.littlehorse.sdk.common.proto.InlineWfSpecDefinition DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.sdk.common.proto.InlineWfSpecDefinition();
  }

  public static io.littlehorse.sdk.common.proto.InlineWfSpecDefinition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InlineWfSpecDefinition>
      PARSER = new com.google.protobuf.AbstractParser<InlineWfSpecDefinition>() {
    @java.lang.Override
    public InlineWfSpecDefinition parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InlineWfSpecDefinition> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InlineWfSpecDefinition> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.sdk.common.proto.InlineWfSpecDefinition getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

