// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: wf_spec.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

@com.google.protobuf.Generated
public interface InlineWfSpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.InlineWfSpec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
   * @return Whether the definition field is set.
   */
  boolean hasDefinition();
  /**
   * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
   * @return The definition.
   */
  io.littlehorse.sdk.common.proto.InlineWfSpecDefinition getDefinition();
  /**
   * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
   */
  io.littlehorse.sdk.common.proto.InlineWfSpecDefinitionOrBuilder getDefinitionOrBuilder();

  /**
   * <pre>
   * Server-generated fingerprint of the canonical definition.
   *
   * Intended for diagnostics, comparison, and integrity validation.
   * It does not make the definition globally addressable.
   * </pre>
   *
   * <code>string checksum = 2;</code>
   * @return The checksum.
   */
  java.lang.String getChecksum();
  /**
   * <pre>
   * Server-generated fingerprint of the canonical definition.
   *
   * Intended for diagnostics, comparison, and integrity validation.
   * It does not make the definition globally addressable.
   * </pre>
   *
   * <code>string checksum = 2;</code>
   * @return The bytes for checksum.
   */
  com.google.protobuf.ByteString
      getChecksumBytes();
}
