// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: wf_spec.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

/**
 * <pre>
 * Immutable, server-normalized snapshot stored in the owning WfRun's partition.
 * Created by RunInlineWf and deleted with its WfRun; not independently writable.
 * </pre>
 *
 * Protobuf type {@code littlehorse.InlineWfSpec}
 */
@com.google.protobuf.Generated
public final class InlineWfSpec extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:littlehorse.InlineWfSpec)
    InlineWfSpecOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      InlineWfSpec.class.getName());
  }
  // Use InlineWfSpec.newBuilder() to construct.
  private InlineWfSpec(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InlineWfSpec() {
    checksum_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpec_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpec_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.littlehorse.sdk.common.proto.InlineWfSpec.class, io.littlehorse.sdk.common.proto.InlineWfSpec.Builder.class);
  }

  private int bitField0_;
  public static final int DEFINITION_FIELD_NUMBER = 1;
  private io.littlehorse.sdk.common.proto.InlineWfSpecDefinition definition_;
  /**
   * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
   * @return Whether the definition field is set.
   */
  @java.lang.Override
  public boolean hasDefinition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
   * @return The definition.
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.InlineWfSpecDefinition getDefinition() {
    return definition_ == null ? io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.getDefaultInstance() : definition_;
  }
  /**
   * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.InlineWfSpecDefinitionOrBuilder getDefinitionOrBuilder() {
    return definition_ == null ? io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.getDefaultInstance() : definition_;
  }

  public static final int CHECKSUM_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object checksum_ = "";
  /**
   * <pre>
   * Server-generated fingerprint of the canonical definition.
   *
   * Intended for diagnostics, comparison, and integrity validation.
   * It does not make the definition globally addressable.
   * </pre>
   *
   * <code>string checksum = 2;</code>
   * @return The checksum.
   */
  @java.lang.Override
  public java.lang.String getChecksum() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checksum_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Server-generated fingerprint of the canonical definition.
   *
   * Intended for diagnostics, comparison, and integrity validation.
   * It does not make the definition globally addressable.
   * </pre>
   *
   * <code>string checksum = 2;</code>
   * @return The bytes for checksum.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChecksumBytes() {
    java.lang.Object ref = checksum_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checksum_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 3;
  private io.littlehorse.sdk.common.proto.InlineWfSpecId id_;
  /**
   * <code>.littlehorse.InlineWfSpecId id = 3;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.littlehorse.InlineWfSpecId id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.InlineWfSpecId getId() {
    return id_ == null ? io.littlehorse.sdk.common.proto.InlineWfSpecId.getDefaultInstance() : id_;
  }
  /**
   * <code>.littlehorse.InlineWfSpecId id = 3;</code>
   */
  @java.lang.Override
  public io.littlehorse.sdk.common.proto.InlineWfSpecIdOrBuilder getIdOrBuilder() {
    return id_ == null ? io.littlehorse.sdk.common.proto.InlineWfSpecId.getDefaultInstance() : id_;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   * @return Whether the createdAt field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getDefinition());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(checksum_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, checksum_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getId());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getCreatedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDefinition());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(checksum_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, checksum_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getId());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCreatedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.littlehorse.sdk.common.proto.InlineWfSpec)) {
      return super.equals(obj);
    }
    io.littlehorse.sdk.common.proto.InlineWfSpec other = (io.littlehorse.sdk.common.proto.InlineWfSpec) obj;

    if (hasDefinition() != other.hasDefinition()) return false;
    if (hasDefinition()) {
      if (!getDefinition()
          .equals(other.getDefinition())) return false;
    }
    if (!getChecksum()
        .equals(other.getChecksum())) return false;
    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDefinition()) {
      hash = (37 * hash) + DEFINITION_FIELD_NUMBER;
      hash = (53 * hash) + getDefinition().hashCode();
    }
    hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
    hash = (53 * hash) + getChecksum().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.littlehorse.sdk.common.proto.InlineWfSpec parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.littlehorse.sdk.common.proto.InlineWfSpec prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Immutable, server-normalized snapshot stored in the owning WfRun's partition.
   * Created by RunInlineWf and deleted with its WfRun; not independently writable.
   * </pre>
   *
   * Protobuf type {@code littlehorse.InlineWfSpec}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:littlehorse.InlineWfSpec)
      io.littlehorse.sdk.common.proto.InlineWfSpecOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.littlehorse.sdk.common.proto.InlineWfSpec.class, io.littlehorse.sdk.common.proto.InlineWfSpec.Builder.class);
    }

    // Construct using io.littlehorse.sdk.common.proto.InlineWfSpec.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetDefinitionFieldBuilder();
        internalGetIdFieldBuilder();
        internalGetCreatedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      definition_ = null;
      if (definitionBuilder_ != null) {
        definitionBuilder_.dispose();
        definitionBuilder_ = null;
      }
      checksum_ = "";
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.littlehorse.sdk.common.proto.WfSpecOuterClass.internal_static_littlehorse_InlineWfSpec_descriptor;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.InlineWfSpec getDefaultInstanceForType() {
      return io.littlehorse.sdk.common.proto.InlineWfSpec.getDefaultInstance();
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.InlineWfSpec build() {
      io.littlehorse.sdk.common.proto.InlineWfSpec result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.littlehorse.sdk.common.proto.InlineWfSpec buildPartial() {
      io.littlehorse.sdk.common.proto.InlineWfSpec result = new io.littlehorse.sdk.common.proto.InlineWfSpec(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.littlehorse.sdk.common.proto.InlineWfSpec result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.definition_ = definitionBuilder_ == null
            ? definition_
            : definitionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.checksum_ = checksum_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.id_ = idBuilder_ == null
            ? id_
            : idBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.littlehorse.sdk.common.proto.InlineWfSpec) {
        return mergeFrom((io.littlehorse.sdk.common.proto.InlineWfSpec)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.littlehorse.sdk.common.proto.InlineWfSpec other) {
      if (other == io.littlehorse.sdk.common.proto.InlineWfSpec.getDefaultInstance()) return this;
      if (other.hasDefinition()) {
        mergeDefinition(other.getDefinition());
      }
      if (!other.getChecksum().isEmpty()) {
        checksum_ = other.checksum_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetDefinitionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              checksum_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.littlehorse.sdk.common.proto.InlineWfSpecDefinition definition_;
    private com.google.protobuf.SingleFieldBuilder<
        io.littlehorse.sdk.common.proto.InlineWfSpecDefinition, io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.Builder, io.littlehorse.sdk.common.proto.InlineWfSpecDefinitionOrBuilder> definitionBuilder_;
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     * @return Whether the definition field is set.
     */
    public boolean hasDefinition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     * @return The definition.
     */
    public io.littlehorse.sdk.common.proto.InlineWfSpecDefinition getDefinition() {
      if (definitionBuilder_ == null) {
        return definition_ == null ? io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.getDefaultInstance() : definition_;
      } else {
        return definitionBuilder_.getMessage();
      }
    }
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     */
    public Builder setDefinition(io.littlehorse.sdk.common.proto.InlineWfSpecDefinition value) {
      if (definitionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        definition_ = value;
      } else {
        definitionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     */
    public Builder setDefinition(
        io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.Builder builderForValue) {
      if (definitionBuilder_ == null) {
        definition_ = builderForValue.build();
      } else {
        definitionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     */
    public Builder mergeDefinition(io.littlehorse.sdk.common.proto.InlineWfSpecDefinition value) {
      if (definitionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          definition_ != null &&
          definition_ != io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.getDefaultInstance()) {
          getDefinitionBuilder().mergeFrom(value);
        } else {
          definition_ = value;
        }
      } else {
        definitionBuilder_.mergeFrom(value);
      }
      if (definition_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     */
    public Builder clearDefinition() {
      bitField0_ = (bitField0_ & ~0x00000001);
      definition_ = null;
      if (definitionBuilder_ != null) {
        definitionBuilder_.dispose();
        definitionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.Builder getDefinitionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetDefinitionFieldBuilder().getBuilder();
    }
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     */
    public io.littlehorse.sdk.common.proto.InlineWfSpecDefinitionOrBuilder getDefinitionOrBuilder() {
      if (definitionBuilder_ != null) {
        return definitionBuilder_.getMessageOrBuilder();
      } else {
        return definition_ == null ?
            io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.getDefaultInstance() : definition_;
      }
    }
    /**
     * <code>.littlehorse.InlineWfSpecDefinition definition = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.littlehorse.sdk.common.proto.InlineWfSpecDefinition, io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.Builder, io.littlehorse.sdk.common.proto.InlineWfSpecDefinitionOrBuilder> 
        internalGetDefinitionFieldBuilder() {
      if (definitionBuilder_ == null) {
        definitionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.littlehorse.sdk.common.proto.InlineWfSpecDefinition, io.littlehorse.sdk.common.proto.InlineWfSpecDefinition.Builder, io.littlehorse.sdk.common.proto.InlineWfSpecDefinitionOrBuilder>(
                getDefinition(),
                getParentForChildren(),
                isClean());
        definition_ = null;
      }
      return definitionBuilder_;
    }

    private java.lang.Object checksum_ = "";
    /**
     * <pre>
     * Server-generated fingerprint of the canonical definition.
     *
     * Intended for diagnostics, comparison, and integrity validation.
     * It does not make the definition globally addressable.
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @return The checksum.
     */
    public java.lang.String getChecksum() {
      java.lang.Object ref = checksum_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checksum_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Server-generated fingerprint of the canonical definition.
     *
     * Intended for diagnostics, comparison, and integrity validation.
     * It does not make the definition globally addressable.
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @return The bytes for checksum.
     */
    public com.google.protobuf.ByteString
        getChecksumBytes() {
      java.lang.Object ref = checksum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checksum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Server-generated fingerprint of the canonical definition.
     *
     * Intended for diagnostics, comparison, and integrity validation.
     * It does not make the definition globally addressable.
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @param value The checksum to set.
     * @return This builder for chaining.
     */
    public Builder setChecksum(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      checksum_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Server-generated fingerprint of the canonical definition.
     *
     * Intended for diagnostics, comparison, and integrity validation.
     * It does not make the definition globally addressable.
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChecksum() {
      checksum_ = getDefaultInstance().getChecksum();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Server-generated fingerprint of the canonical definition.
     *
     * Intended for diagnostics, comparison, and integrity validation.
     * It does not make the definition globally addressable.
     * </pre>
     *
     * <code>string checksum = 2;</code>
     * @param value The bytes for checksum to set.
     * @return This builder for chaining.
     */
    public Builder setChecksumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      checksum_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private io.littlehorse.sdk.common.proto.InlineWfSpecId id_;
    private com.google.protobuf.SingleFieldBuilder<
        io.littlehorse.sdk.common.proto.InlineWfSpecId, io.littlehorse.sdk.common.proto.InlineWfSpecId.Builder, io.littlehorse.sdk.common.proto.InlineWfSpecIdOrBuilder> idBuilder_;
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     * @return The id.
     */
    public io.littlehorse.sdk.common.proto.InlineWfSpecId getId() {
      if (idBuilder_ == null) {
        return id_ == null ? io.littlehorse.sdk.common.proto.InlineWfSpecId.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     */
    public Builder setId(io.littlehorse.sdk.common.proto.InlineWfSpecId value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
      } else {
        idBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     */
    public Builder setId(
        io.littlehorse.sdk.common.proto.InlineWfSpecId.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     */
    public Builder mergeId(io.littlehorse.sdk.common.proto.InlineWfSpecId value) {
      if (idBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          id_ != null &&
          id_ != io.littlehorse.sdk.common.proto.InlineWfSpecId.getDefaultInstance()) {
          getIdBuilder().mergeFrom(value);
        } else {
          id_ = value;
        }
      } else {
        idBuilder_.mergeFrom(value);
      }
      if (id_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      id_ = null;
      if (idBuilder_ != null) {
        idBuilder_.dispose();
        idBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     */
    public io.littlehorse.sdk.common.proto.InlineWfSpecId.Builder getIdBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     */
    public io.littlehorse.sdk.common.proto.InlineWfSpecIdOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            io.littlehorse.sdk.common.proto.InlineWfSpecId.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.littlehorse.InlineWfSpecId id = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.littlehorse.sdk.common.proto.InlineWfSpecId, io.littlehorse.sdk.common.proto.InlineWfSpecId.Builder, io.littlehorse.sdk.common.proto.InlineWfSpecIdOrBuilder> 
        internalGetIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.littlehorse.sdk.common.proto.InlineWfSpecId, io.littlehorse.sdk.common.proto.InlineWfSpecId.Builder, io.littlehorse.sdk.common.proto.InlineWfSpecIdOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:littlehorse.InlineWfSpec)
  }

  // @@protoc_insertion_point(class_scope:littlehorse.InlineWfSpec)
  private static final io.littlehorse.sdk.common.proto.InlineWfSpec DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.littlehorse.sdk.common.proto.InlineWfSpec();
  }

  public static io.littlehorse.sdk.common.proto.InlineWfSpec getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InlineWfSpec>
      PARSER = new com.google.protobuf.AbstractParser<InlineWfSpec>() {
    @java.lang.Override
    public InlineWfSpec parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InlineWfSpec> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InlineWfSpec> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.littlehorse.sdk.common.proto.InlineWfSpec getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

