// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

@com.google.protobuf.Generated
public interface PutVariableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.PutVariableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Exact ID of the existing variable to modify.
   * </pre>
   *
   * <code>.littlehorse.VariableId id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * Exact ID of the existing variable to modify.
   * </pre>
   *
   * <code>.littlehorse.VariableId id = 1;</code>
   * @return The id.
   */
  io.littlehorse.sdk.common.proto.VariableId getId();
  /**
   * <pre>
   * Exact ID of the existing variable to modify.
   * </pre>
   *
   * <code>.littlehorse.VariableId id = 1;</code>
   */
  io.littlehorse.sdk.common.proto.VariableIdOrBuilder getIdOrBuilder();

  /**
   * <pre>
   * Replacement value. An empty VariableValue represents null.
   * </pre>
   *
   * <code>.littlehorse.VariableValue value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * Replacement value. An empty VariableValue represents null.
   * </pre>
   *
   * <code>.littlehorse.VariableValue value = 2;</code>
   * @return The value.
   */
  io.littlehorse.sdk.common.proto.VariableValue getValue();
  /**
   * <pre>
   * Replacement value. An empty VariableValue represents null.
   * </pre>
   *
   * <code>.littlehorse.VariableValue value = 2;</code>
   */
  io.littlehorse.sdk.common.proto.VariableValueOrBuilder getValueOrBuilder();
}
