// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: service.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

@com.google.protobuf.Generated
public interface RunInlineWfRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:littlehorse.RunInlineWfRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.littlehorse.InlineWfSpecDefinition wf_spec = 1;</code>
   * @return Whether the wfSpec field is set.
   */
  boolean hasWfSpec();
  /**
   * <code>.littlehorse.InlineWfSpecDefinition wf_spec = 1;</code>
   * @return The wfSpec.
   */
  io.littlehorse.sdk.common.proto.InlineWfSpecDefinition getWfSpec();
  /**
   * <code>.littlehorse.InlineWfSpecDefinition wf_spec = 1;</code>
   */
  io.littlehorse.sdk.common.proto.InlineWfSpecDefinitionOrBuilder getWfSpecOrBuilder();

  /**
   * <code>map&lt;string, .littlehorse.VariableValue&gt; variables = 2;</code>
   */
  int getVariablesCount();
  /**
   * <code>map&lt;string, .littlehorse.VariableValue&gt; variables = 2;</code>
   */
  boolean containsVariables(
      java.lang.String key);
  /**
   * Use {@link #getVariablesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.VariableValue>
  getVariables();
  /**
   * <code>map&lt;string, .littlehorse.VariableValue&gt; variables = 2;</code>
   */
  java.util.Map<java.lang.String, io.littlehorse.sdk.common.proto.VariableValue>
  getVariablesMap();
  /**
   * <code>map&lt;string, .littlehorse.VariableValue&gt; variables = 2;</code>
   */
  /* nullable */
io.littlehorse.sdk.common.proto.VariableValue getVariablesOrDefault(
      java.lang.String key,
      /* nullable */
io.littlehorse.sdk.common.proto.VariableValue defaultValue);
  /**
   * <code>map&lt;string, .littlehorse.VariableValue&gt; variables = 2;</code>
   */
  io.littlehorse.sdk.common.proto.VariableValue getVariablesOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Reusing an existing run ID returns ALREADY_EXISTS, as with RunWf.
   * </pre>
   *
   * <code>optional string id = 3;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * Reusing an existing run ID returns ALREADY_EXISTS, as with RunWf.
   * </pre>
   *
   * <code>optional string id = 3;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Reusing an existing run ID returns ALREADY_EXISTS, as with RunWf.
   * </pre>
   *
   * <code>optional string id = 3;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
