// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: wf_run.proto
// Protobuf Java Version: 4.32.1

package io.littlehorse.sdk.common.proto;

@com.google.protobuf.Generated
public final class WfRunOuterClass extends com.google.protobuf.GeneratedFile {
  private WfRunOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      WfRunOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_WfRun_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_WfRun_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_WfRun_ParentTriggerReference_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_WfRun_ParentTriggerReference_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_WfRun_MigrationVariablesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_WfRun_MigrationVariablesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ThreadRun_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_ThreadRun_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_InactiveThreadRun_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_InactiveThreadRun_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ArchivedThreadRunInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_ArchivedThreadRunInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_QueuedThreadRunInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_QueuedThreadRunInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_QueuedThreadRunInfo_InputVarsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_QueuedThreadRunInfo_InputVarsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_FailureBeingHandled_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_FailureBeingHandled_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PendingInterrupt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_PendingInterrupt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PendingFailureHandler_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_PendingFailureHandler_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PendingInterruptHaltReason_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_PendingInterruptHaltReason_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_PendingFailureHandlerHaltReason_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_PendingFailureHandlerHaltReason_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_HandlingFailureHaltReason_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_HandlingFailureHaltReason_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_HaltedByParentNodeHaltReason_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_HaltedByParentNodeHaltReason_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ParentHalted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_ParentHalted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_Interrupted_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_Interrupted_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ManualHalt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_ManualHalt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_littlehorse_ThreadHaltReason_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_littlehorse_ThreadHaltReason_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014wf_run.proto\022\013littlehorse\032\037google/prot" +
      "obuf/timestamp.proto\032\022common_enums.proto" +
      "\032\017object_id.proto\032\025type_definition.proto" +
      "\032\030workflow_migration.proto\032\rwf_spec.prot" +
      "o\"\353\010\n\005WfRun\022 \n\002id\030\001 \001(\0132\024.littlehorse.Wf" +
      "RunId\022+\n\nwf_spec_id\030\002 \001(\0132\025.littlehorse." +
      "WfSpecIdH\000\0227\n\016inline_wf_spec\030\017 \001(\0132\031.lit" +
      "tlehorse.InlineWfSpecB\002\030\001H\000\0228\n\021inline_wf" +
      "_spec_id\030\020 \001(\0132\033.littlehorse.InlineWfSpe" +
      "cIdH\000\0223\n\024old_wf_spec_versions\030\003 \003(\0132\025.li" +
      "ttlehorse.WfSpecId\022%\n\006status\030\004 \001(\0162\025.lit" +
      "tlehorse.LHStatus\022!\n\031greatest_threadrun_" +
      "number\030\005 \001(\005\022.\n\nstart_time\030\006 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\0221\n\010end_time\030\007 \001(\0132\032" +
      ".google.protobuf.TimestampH\001\210\001\001\022+\n\013threa" +
      "d_runs\030\010 \003(\0132\026.littlehorse.ThreadRun\0229\n\022" +
      "pending_interrupts\030\t \003(\0132\035.littlehorse.P" +
      "endingInterrupt\022<\n\020pending_failures\030\n \003(" +
      "\0132\".littlehorse.PendingFailureHandler\022F\n" +
      "\016parent_trigger\030\013 \001(\0132).littlehorse.WfRu" +
      "n.ParentTriggerReferenceH\002\210\001\001\022H\n\032workflo" +
      "w_migration_plan_id\030\014 \001(\0132$.littlehorse." +
      "WorkflowMigrationPlanId\022G\n\023migration_var" +
      "iables\030\r \003(\0132*.littlehorse.WfRun.Migrati" +
      "onVariablesEntry\022\030\n\020thread_run_queue\030\016 \003" +
      "(\005\032\231\001\n\026ParentTriggerReference\0223\n\023trigger" +
      "ing_node_run\030\001 \001(\0132\026.littlehorse.NodeRun" +
      "Id\0225\n\020waiting_node_run\030\002 \001(\0132\026.littlehor" +
      "se.NodeRunIdH\000\210\001\001B\023\n\021_waiting_node_run\032U" +
      "\n\027MigrationVariablesEntry\022\013\n\003key\030\001 \001(\t\022)" +
      "\n\005value\030\002 \001(\0132\032.littlehorse.MigrationVar" +
      "s:\0028\001B\020\n\016wf_spec_sourceB\013\n\t_end_timeB\021\n\017" +
      "_parent_trigger\"\205\006\n\tThreadRun\022)\n\nwf_spec" +
      "_id\030\001 \001(\0132\025.littlehorse.WfSpecId\022\016\n\006numb" +
      "er\030\002 \001(\005\022%\n\006status\030\003 \001(\0162\025.littlehorse.L" +
      "HStatus\022\030\n\020thread_spec_name\030\004 \001(\t\022.\n\nsta" +
      "rt_time\030\005 \001(\0132\032.google.protobuf.Timestam" +
      "p\0221\n\010end_time\030\006 \001(\0132\032.google.protobuf.Ti" +
      "mestampH\000\210\001\001\022\032\n\rerror_message\030\007 \001(\tH\001\210\001\001" +
      "\022\030\n\020child_thread_ids\030\010 \003(\005\022\035\n\020parent_thr" +
      "ead_id\030\t \001(\005H\002\210\001\001\0223\n\014halt_reasons\030\n \003(\0132" +
      "\035.littlehorse.ThreadHaltReason\022?\n\024interr" +
      "upt_trigger_id\030\013 \001(\0132\034.littlehorse.Exter" +
      "nalEventIdH\003\210\001\001\022D\n\025failure_being_handled" +
      "\030\014 \001(\0132 .littlehorse.FailureBeingHandled" +
      "H\004\210\001\001\022\035\n\025current_node_position\030\r \001(\005\022\037\n\027" +
      "handled_failed_children\030\016 \003(\005\022%\n\004type\030\017 " +
      "\001(\0162\027.littlehorse.ThreadType\022/\n\006output\030\020" +
      " \001(\0132\032.littlehorse.VariableValueH\005\210\001\001B\013\n" +
      "\t_end_timeB\020\n\016_error_messageB\023\n\021_parent_" +
      "thread_idB\027\n\025_interrupt_trigger_idB\030\n\026_f" +
      "ailure_being_handledB\t\n\007_output\"\354\001\n\021Inac" +
      "tiveThreadRun\022*\n\nthread_run\030\001 \001(\0132\026.litt" +
      "lehorse.ThreadRun\0226\n\010archived\030\002 \001(\0132\".li" +
      "ttlehorse.ArchivedThreadRunInfoH\000\0222\n\006que" +
      "ued\030\003 \001(\0132 .littlehorse.QueuedThreadRunI" +
      "nfoH\000\022,\n\002id\030\004 \001(\0132 .littlehorse.Inactive" +
      "ThreadRunIdB\021\n\017inactive_reason\"\027\n\025Archiv" +
      "edThreadRunInfo\"\250\001\n\023QueuedThreadRunInfo\022" +
      "C\n\ninput_vars\030\001 \003(\0132/.littlehorse.Queued" +
      "ThreadRunInfo.InputVarsEntry\032L\n\016InputVar" +
      "sEntry\022\013\n\003key\030\001 \001(\t\022)\n\005value\030\002 \001(\0132\032.lit" +
      "tlehorse.VariableValue:\0028\001\"c\n\023FailureBei" +
      "ngHandled\022\031\n\021thread_run_number\030\001 \001(\005\022\031\n\021" +
      "node_run_position\030\002 \001(\005\022\026\n\016failure_numbe" +
      "r\030\003 \001(\005\"\205\001\n\020PendingInterrupt\0227\n\021external" +
      "_event_id\030\001 \001(\0132\034.littlehorse.ExternalEv" +
      "entId\022\031\n\021handler_spec_name\030\002 \001(\t\022\035\n\025inte" +
      "rrupted_thread_id\030\003 \001(\005\"M\n\025PendingFailur" +
      "eHandler\022\031\n\021failed_thread_run\030\001 \001(\005\022\031\n\021h" +
      "andler_spec_name\030\002 \001(\t\"U\n\032PendingInterru" +
      "ptHaltReason\0227\n\021external_event_id\030\001 \001(\0132" +
      "\034.littlehorse.ExternalEventId\"<\n\037Pending" +
      "FailureHandlerHaltReason\022\031\n\021node_run_pos" +
      "ition\030\001 \001(\005\"6\n\031HandlingFailureHaltReason" +
      "\022\031\n\021handler_thread_id\030\001 \001(\005\"c\n\034HaltedByP" +
      "arentNodeHaltReason\022 \n\030parent_thread_run" +
      "_number\030\001 \001(\005\022!\n\031waiting_node_run_positi" +
      "on\030\002 \001(\005\"(\n\014ParentHalted\022\030\n\020parent_threa" +
      "d_id\030\001 \001(\005\"*\n\013Interrupted\022\033\n\023interrupt_t" +
      "hread_id\030\001 \001(\005\"&\n\nManualHalt\022\030\n\017meaning_" +
      "of_life\030\211\001 \001(\010\"\313\003\n\020ThreadHaltReason\0222\n\rp" +
      "arent_halted\030\001 \001(\0132\031.littlehorse.ParentH" +
      "altedH\000\022/\n\013interrupted\030\002 \001(\0132\030.littlehor" +
      "se.InterruptedH\000\022D\n\021pending_interrupt\030\003 " +
      "\001(\0132\'.littlehorse.PendingInterruptHaltRe" +
      "asonH\000\022G\n\017pending_failure\030\004 \001(\0132,.little" +
      "horse.PendingFailureHandlerHaltReasonH\000\022" +
      "B\n\020handling_failure\030\005 \001(\0132&.littlehorse." +
      "HandlingFailureHaltReasonH\000\022.\n\013manual_ha" +
      "lt\030\006 \001(\0132\027.littlehorse.ManualHaltH\000\022E\n\020h" +
      "alted_by_parent\030\007 \001(\0132).littlehorse.Halt" +
      "edByParentNodeHaltReasonH\000B\010\n\006reason*K\n\n" +
      "ThreadType\022\016\n\nENTRYPOINT\020\000\022\t\n\005CHILD\020\001\022\r\n" +
      "\tINTERRUPT\020\002\022\023\n\017FAILURE_HANDLER\020\003BM\n\037io." +
      "littlehorse.sdk.common.protoP\001Z\t.;lhprot" +
      "o\252\002\034LittleHorse.Sdk.Common.Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          io.littlehorse.sdk.common.proto.CommonEnums.getDescriptor(),
          io.littlehorse.sdk.common.proto.ObjectId.getDescriptor(),
          io.littlehorse.sdk.common.proto.TypeDefinitionOuterClass.getDescriptor(),
          io.littlehorse.sdk.common.proto.WorkflowMigration.getDescriptor(),
          io.littlehorse.sdk.common.proto.WfSpecOuterClass.getDescriptor(),
        });
    internal_static_littlehorse_WfRun_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_littlehorse_WfRun_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_WfRun_descriptor,
        new java.lang.String[] { "Id", "WfSpecId", "InlineWfSpec", "InlineWfSpecId", "OldWfSpecVersions", "Status", "GreatestThreadrunNumber", "StartTime", "EndTime", "ThreadRuns", "PendingInterrupts", "PendingFailures", "ParentTrigger", "WorkflowMigrationPlanId", "MigrationVariables", "ThreadRunQueue", "WfSpecSource", });
    internal_static_littlehorse_WfRun_ParentTriggerReference_descriptor =
      internal_static_littlehorse_WfRun_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_WfRun_ParentTriggerReference_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_WfRun_ParentTriggerReference_descriptor,
        new java.lang.String[] { "TriggeringNodeRun", "WaitingNodeRun", });
    internal_static_littlehorse_WfRun_MigrationVariablesEntry_descriptor =
      internal_static_littlehorse_WfRun_descriptor.getNestedTypes().get(1);
    internal_static_littlehorse_WfRun_MigrationVariablesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_WfRun_MigrationVariablesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_littlehorse_ThreadRun_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_littlehorse_ThreadRun_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_ThreadRun_descriptor,
        new java.lang.String[] { "WfSpecId", "Number", "Status", "ThreadSpecName", "StartTime", "EndTime", "ErrorMessage", "ChildThreadIds", "ParentThreadId", "HaltReasons", "InterruptTriggerId", "FailureBeingHandled", "CurrentNodePosition", "HandledFailedChildren", "Type", "Output", });
    internal_static_littlehorse_InactiveThreadRun_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_littlehorse_InactiveThreadRun_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_InactiveThreadRun_descriptor,
        new java.lang.String[] { "ThreadRun", "Archived", "Queued", "Id", "InactiveReason", });
    internal_static_littlehorse_ArchivedThreadRunInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_littlehorse_ArchivedThreadRunInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_ArchivedThreadRunInfo_descriptor,
        new java.lang.String[] { });
    internal_static_littlehorse_QueuedThreadRunInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_littlehorse_QueuedThreadRunInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_QueuedThreadRunInfo_descriptor,
        new java.lang.String[] { "InputVars", });
    internal_static_littlehorse_QueuedThreadRunInfo_InputVarsEntry_descriptor =
      internal_static_littlehorse_QueuedThreadRunInfo_descriptor.getNestedTypes().get(0);
    internal_static_littlehorse_QueuedThreadRunInfo_InputVarsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_QueuedThreadRunInfo_InputVarsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_littlehorse_FailureBeingHandled_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_littlehorse_FailureBeingHandled_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_FailureBeingHandled_descriptor,
        new java.lang.String[] { "ThreadRunNumber", "NodeRunPosition", "FailureNumber", });
    internal_static_littlehorse_PendingInterrupt_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_littlehorse_PendingInterrupt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_PendingInterrupt_descriptor,
        new java.lang.String[] { "ExternalEventId", "HandlerSpecName", "InterruptedThreadId", });
    internal_static_littlehorse_PendingFailureHandler_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_littlehorse_PendingFailureHandler_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_PendingFailureHandler_descriptor,
        new java.lang.String[] { "FailedThreadRun", "HandlerSpecName", });
    internal_static_littlehorse_PendingInterruptHaltReason_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_littlehorse_PendingInterruptHaltReason_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_PendingInterruptHaltReason_descriptor,
        new java.lang.String[] { "ExternalEventId", });
    internal_static_littlehorse_PendingFailureHandlerHaltReason_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_littlehorse_PendingFailureHandlerHaltReason_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_PendingFailureHandlerHaltReason_descriptor,
        new java.lang.String[] { "NodeRunPosition", });
    internal_static_littlehorse_HandlingFailureHaltReason_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_littlehorse_HandlingFailureHaltReason_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_HandlingFailureHaltReason_descriptor,
        new java.lang.String[] { "HandlerThreadId", });
    internal_static_littlehorse_HaltedByParentNodeHaltReason_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_littlehorse_HaltedByParentNodeHaltReason_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_HaltedByParentNodeHaltReason_descriptor,
        new java.lang.String[] { "ParentThreadRunNumber", "WaitingNodeRunPosition", });
    internal_static_littlehorse_ParentHalted_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_littlehorse_ParentHalted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_ParentHalted_descriptor,
        new java.lang.String[] { "ParentThreadId", });
    internal_static_littlehorse_Interrupted_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_littlehorse_Interrupted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_Interrupted_descriptor,
        new java.lang.String[] { "InterruptThreadId", });
    internal_static_littlehorse_ManualHalt_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_littlehorse_ManualHalt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_ManualHalt_descriptor,
        new java.lang.String[] { "MeaningOfLife", });
    internal_static_littlehorse_ThreadHaltReason_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_littlehorse_ThreadHaltReason_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_littlehorse_ThreadHaltReason_descriptor,
        new java.lang.String[] { "ParentHalted", "Interrupted", "PendingInterrupt", "PendingFailure", "HandlingFailure", "ManualHalt", "HaltedByParent", "Reason", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
    io.littlehorse.sdk.common.proto.CommonEnums.getDescriptor();
    io.littlehorse.sdk.common.proto.ObjectId.getDescriptor();
    io.littlehorse.sdk.common.proto.TypeDefinitionOuterClass.getDescriptor();
    io.littlehorse.sdk.common.proto.WorkflowMigration.getDescriptor();
    io.littlehorse.sdk.common.proto.WfSpecOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
